name: Release nuget

on:
  push:
    tags: "nuget-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release      
      
    - name: Create the package - Client
      run: dotnet pack --configuration Release MyDataFlowPattern/MyDataFlowPattern.csproj /p:Version=${GITHUB_REF#refs/tags/nuget-}

    - name: Publish the package to GPR - Client
      run: dotnet nuget push MyDataFlowPattern/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
